---
# Provision EC2 instances
# Based heavily on the Ansible guide and documentation on AWS / EC2:
# http://docs.ansible.com/guide_aws.html
# http://docs.ansible.com/ec2_module.html


# Provision the EC2 instanses using Ansible ec2 module
- name: Provision EC2 instances
  hosts: local
  sudo: no
  connection: local
  gather_facts: False

  tasks:
    # Get encrypted EC2 key(s) from Ansible vault
    - name: Install EC2 deploy user private key
      shell: echo "{{ ec2_deploy_key }}" > {{ ec2_deploy_key_file }}  && chmod 600 {{ ec2_deploy_key_file }}

    # Add SSH key to Ansible
    - name: Add SSH key to ansible user with ssh-add
      shell: ssh-add {{ ec2_deploy_key_file }}

    # Spin up the EC3 instances
    - name: Launch "Webserver" instances
      ec2: 
        instance_type: t2.micro
        image: ami-b83c0aa5
        region: eu-central-1
        group: default
        monitoring: yes
        wait: yes
        key_name: aaawg_ec2_deploy
        count: 2 
        instance_tags:
          Name: Webserver
      register: ec2

    # Wait for the EC2 instances to come up
    - name: Wait for SSH to come up on the EC2 instances
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=300 state=started
      with_items: ec2.instances

