---
# tasks file for aaawg-nginx

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=true
  notify:
    - Start nginx
  tags: 
    - nginx
    - install

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: 
    - restart nginx
  tags:
    - nginx
    - config

- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
  tags: 
    - nginx
    - config

- name: Make sure nginx is running and enabled to start at boot           
  service: name=nginx state=running enabled=yes                           
  tags:                                                                        
    - nginx
    - enable
